### ISSUE TITLE
Suggestion: Change title colour

### ISSUE THREAD

**Issue by worknhard99** [fred-hausmann/demo#1]
I think it looks better if the main title is more orange.
The sytling rule could be changed like this:

```css
h1 {
  color: #e5a73c;
}
```
